language: node_js
sudo: required
node_js:
  - "5"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libkrb5-dev
      - libcairo2-dev 
      - libjpeg8-dev 
      - libpango1.0-dev 
      - libgif-dev 
      - build-essential 
      - g++-4.8
env:
  - CXX=g++-4.8
services:
  - mongodb
before_script:
  - npm install node-gyp@latest
  - npm install -g gulp
  - npm install -g bower
  - cd node_modules/jade-press & bower install & cd ../..