language: node_js
sudo: required
node_js:
  - "5"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libkrb5-dev
      - libcairo2-dev 
      - libjpeg8-dev 
      - libpango1.0-dev 
      - libgif-dev 
      - build-essential 
      - g++-4.8
      - openjdk-7-jre
env:
  - CXX=g++-4.8
services:
  - mongodb
before_script:
  - npm install -g bower