language: node_js
sudo: required
node_js:
  - "5"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libkrb5-dev
      - libcairo2-dev 
      - libjpeg8-dev 
      - libpango1.0-dev 
      - libgif-dev 
      - build-essential 
      - g++-4.8
      - openjdk-7-jre
env:
  - CXX=g++-4.8
services:
  - mongodb
before_install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
before_script:
  - npm install -g bower